require ("prototypes.entity")
require ("prototypes.item")
require ("prototypes.recipe")
require ("prototypes.beam")
require ("prototypes.hotkey")
require ("prototypes.style")
require ("prototypes.sprite")